# Generated by Django 4.0.3 on 2022-04-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korean_name', models.CharField(max_length=50)),
                ('english_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('my_name', models.TextField()),
            ],
            options={
                'db_table': 'drinks',
            },
        ),
    ]
